backend:
  name: git-gateway
  branch: devel

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "gallery" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Gallery Item" # Used in the UI, ie.: "New Post"
    folder: "site/content/gallery" # The path to the folder where the documents are stored
    filter: {field: "isIndex"}
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Medium", name: "medium", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "words" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Word Item" # Used in the UI, ie.: "New Post"
    folder: "site/content/words" # The path to the folder where the documents are stored
    filter: {field: "isIndex"}
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Format", name: "format", widget: "string"}
      - {label: "Publication", name: "publication", widget: "string", required: false}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Year", name: "year", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News Item" # Used in the UI, ie.: "New Post"
    folder: "site/content/news" # The path to the folder where the documents are stored
    filter: {field: "isIndex"}
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "day", widget: "datetime", required: false}
      - {label: "Snippet", name: "snippet", widget: "string", required: false}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}